export enum RequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  HCM_DEDUCT_PENDING = 'HCM_DEDUCT_PENDING',
  CANCELLATION_CREDIT_PENDING = 'CANCELLATION_CREDIT_PENDING',
  RETRY_EXHAUSTED = 'RETRY_EXHAUSTED',
}

export const ACTIVE_STATUSES: RequestStatus[] = [
  RequestStatus.PENDING,
  RequestStatus.HCM_DEDUCT_PENDING,
];

export const ASYNC_PENDING_STATUSES: RequestStatus[] = [
  RequestStatus.HCM_DEDUCT_PENDING,
  RequestStatus.CANCELLATION_CREDIT_PENDING,
];
